### ISSUE TITLE
Zone network too common

### ISSUE THREAD

**Issue by tylerflint** [vagrant-smartos/vagrant-smartos-zones#30]
Currently, the zone network is 10.0.0.0/8 which is also a very common private address space. To potentially reduce collisions, this should be switched initially to 172.16.0.0/12. Ideally, this can be configurable.

**Comment by sax** [comment]
I think this makes more sense to be configurable. I'm pretty sure that as soon as I hard-coded it to 172 it would cause problems for someone else.

Do you want to put together a pull request? Otherwise I'll assign this to myself.

**Comment by tylerflint** [comment]
I agree, a configurable option seems to be the best solution. I'm trying to think about how best to expose this... We could simply allow one of three networks: 10.0.0.0/8, 172.168.0.0/12, or 192.168.0.0/16. Hmmm... I wonder if I could parse a cidr and make that work...

**Comment by sax** [comment]
There is a cidr gem, though if my memory is correct its API is a little backwards from what we'd want here. Still usable though.

I agree that setting the configuration to a network using cidr notation seems most useful. Then when creating a zone we can pick an address on that network. I remember we talked a while ago about the plugin needing to keep track of IPs that it assigns... not sure if we're at the point of needing that yet, or if we should still assign `.1` and `.2` arbitrarily.

**Comment by sax** [comment]
I'm going to play around with making this dynamic based on configuration. I was going to add the following zone configuration option:

```ruby
config.zone.network = '172.16.0.0/16'
```

But I just realized that this might be better as a plugin-level configuration:

```shell
vagrant zones config network 172.16.0.0/16
```

That way you can change it depending on your current location, without having to check it into your Vagrantfile.

**Comment by sax** [comment]
It was the https://rubygems.org/gems/netaddr gem that I was thinking of. It's pretty nice, actually.
