### ISSUE TITLE
default Vagrant file & config.ssh.insert_key = false

### ISSUE THREAD

**Issue by neurogenesis** [vagrant-smartos/vagrant-smartos-zones#31]
This is more a comment on the project's README.md. The Vagrantfile referenced in the curl statement for installation doesn't appear to work without adding the option "config.ssh.insert_key = false".

This may be a limitation of the smart-os plugin, but the example should use a working version of the Vagrantfile until that's been fixed.

**Comment by sax** [comment]
Ah, yeah. That was a recent change to Vagrant that hasn't yet been addressed in the plugin. I'll update the readme and examples.

**Comment by sax** [comment]
This is fixed in this commit : https://github.com/vagrant-smartos/vagrant-smartos-zones/commit/adb2cefd7ed4a14664f6432aa11f1283c4b68399

Thanks for pointing this out!
