### ISSUE TITLE
2021 vagrant box

### ISSUE THREAD

**Issue by kasperk81** [vagrant-smartos/vagrant-smartos-zones#39]
@sax, could you please publish an update with SmartOS 2021? Thanks!

**Comment by sax** [comment]
I will not have much time to look at this in the near future. That said, I would be happy to test/merge a pull request, if you have the time to make one. Otherwise, if you have any pointers, stack traces or other artifacts demonstrating what is not working, that would be really helpful when I can carve out time.

**Comment by kasperk81** [comment]
Actually my request was about pushing an update to the existing box: https://app.vagrantup.com/livinginthepast/boxes/smartos-base64 with 2021 image.

Something like [`vagrant cloud box update`](https://www.vagrantup.com/docs/cli/cloud#cloud-box-update) with latest 2021 base image from https://wiki.smartos.org/download-smartos/. Does it happen through the CI or could you manually update one?

Thanks!

**Comment by sax** [comment]
Ah, ok. I have [another repo](https://github.com/vagrant-smartos/vagrant-smartos-packager) where I built that, but I haven't touched it in... ooof... 7 years. I'll take a look when I get some time.

**Comment by kasperk81** [comment]
Cool. if it is all scripted, maybe a GitHub Actions script can run once a month and check if there is a newer image available upstream then trigger the other action which published to vagrant cloud without manual intervention.

**Comment by kasperk81** [comment]
Closing it in favor of https://github.com/vagrant-smartos/vagrant-smartos-packager/issues/7. If CI cron-job sound interesting, I can prepare a PR (it will just require encrypted token of vagrant account).

**Comment by sax** [comment]
If you have time to look at vagrant-smartos-packager in the next few days to see if there are required changes based on SmartOS development within the last 7 years, that would be more directly helpful that setting up github actions. CI is much simpler for me to drop in, if the scripts themselves work.

**Comment by kasperk81** [comment]
I had to apply:

```diff
diff --git a/bin/mksmartvm b/bin/mksmartvm
index 8b80da8..cfb8cb9 100755
--- a/bin/mksmartvm
+++ b/bin/mksmartvm
@@ -17,8 +17,8 @@ usage() {
   echo "  -p --sshport    SSH port to forward (default 2222)"
 }
 
-DISKSIZE="32"
-MEMSIZE="1024"
+DISKSIZE="100"
+MEMSIZE="2048"
 SSHPORT="2222"
 
 while getopts ":d:m:p:" arg; do
@@ -39,4 +39,4 @@ echo
 echo "Starting Virtual Machine"
 echo "  Hint: use defaults"
 echo "  Hint: set root password to 'vagrant'"
-VirtualBox --startvm "${vmname}" &
+VirtualBoxVM --startvm "${vmname}" &
```

as startvm flag only works with vboxmanagevm since v6. It has created the latest virtual machine on latest MBP BigSur (and latest VirtualBox), and entered the SmartOS setup. After that i followed the rest of the instructions from readme and boxified succeeded without any further modifications. So it's ready. :)
